# Generated by Django 6.0.5 on 2026-05-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="place_id",
            field=models.IntegerField(),
        ),
    ]
