# Generated by Django 6.0.5 on 2026-05-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visit", "0002_alter_visit_place_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
